CLASS zcl_29_vat_ind_log_c460 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
   data: vat_ind type string.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_29_vat_ind_log_c460 IMPLEMENTATION.
ENDCLASS.
