CLASS zcl_12_friends_log_c460 DEFINITION
  PUBLIC
  FINAL
  CREATE PRIVATE "PROTECTED "PUBLIC
  GLOBAL FRIENDS zcl_13_friends_log_c460.

  PUBLIC SECTION.
  PROTECTED SECTION.
    DATA: protected_attr TYPE string.
  PRIVATE SECTION.
    DATA: private_attr TYPE string.
ENDCLASS.



CLASS zcl_12_friends_log_c460 IMPLEMENTATION.
ENDCLASS.
